# This is a basic workflow to help you get started with Actions

name: Bitbake raspberrypi

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dunfell branch
  push:
    branches: [ dunfell ]
  pull_request:
    branches: [ dunfell ]
  schedule:
    - cron: '0 12 * * 5'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TARGET_VERSION: dunfell

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  bitbake-raspberrypi:

    strategy:
      matrix:
        target_machine: [raspberrypi3-64, raspberrypi3, raspberrypi0-wifi]
        tensorflow_version: [2.8.1, 2.7.2, 2.6.4, 2.5.3, 2.4.4, 2.3.4]

    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      # Install essential host packages
      - name: Install Pakages
        run: |
          sudo apt-get update
          sudo apt-get -y install gawk wget git-core diffstat unzip texinfo gcc-multilib build-essential chrpath socat cpio python3 python3-pip python3-pexpect xz-utils debianutils iputils-ping python3-git python3-jinja2 libegl1-mesa libsdl1.2-dev pylint3 xterm
          sudo apt-get clean
      
      # Check space before cleanup
      - name: Check space before cleanup
        run: |
          df -h
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          df -h
          
      # checkout repository
      - name: Clone poky, meta-raspberrypi, meta-openembedded
        run: |
          git clone -b ${TARGET_VERSION} git://git.yoctoproject.org/poky.git
          git clone -b ${TARGET_VERSION} git://git.yoctoproject.org/meta-raspberrypi
          git clone -b ${TARGET_VERSION} git://git.openembedded.org/meta-openembedded
        working-directory: ../

      # Run bitbake python3-tensorflow-lite and cpp-tensorflow-lite
      - name: Bitbake MACHINE=${{ matrix.target_machine }}, TensorFlow-Lite ${{ matrix.tensorflow_version }}
        run: |
          source poky/oe-init-build-env rpi-build
          bitbake-layers add-layer ../meta-openembedded/meta-oe/
          bitbake-layers add-layer ../meta-openembedded/meta-python/
          bitbake-layers add-layer ../meta-tensorflow-lite/
          bitbake-layers add-layer ../meta-raspberrypi/
          export BITBAKE_OPTION="python3-tensorflow-lite"
          case "${{ matrix.tensorflow_version }}" in
          2.8.*|2.7.*|2.6.*)
            export PREFERRED_VERSION_CPP=PREFERRED_VERSION_cpp-tensorflow-lite=\"${{ matrix.tensorflow_version }}\"
            export BITBAKE_OPTION="${BITBAKE_OPTION} cpp-tensorflow-lite"
            ;;
          esac
          cat <<EOF> conf/auto.conf
          PREFERRED_VERSION_python3-tensorflow-lite="${{ matrix.tensorflow_version }}"
          ${PREFERRED_VERSION_CPP}
          EOF
          cat conf/auto.conf
          MACHINE=${{matrix.target_machine}} bitbake ${BITBAKE_OPTION}
        working-directory: ../
